# shamefullyHoist: true
saveExact: true
autoDedupe: true
saveTypes: true

minimumReleaseAge: 960 # 16 hours in minutes
minimumReleaseAgeExcludePrune: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days in minutes
trustPolicyExclude: []

audit:
  ignore: []
  ignorePrune: true

allowBuilds:
  lefthook@2.1.16: true

  esbuild: false
  unrs-resolver: false
  lefthook: set this to true or false

dedupePeers: true
strictPeerDependencies: false
