import {eslintConfig} from 'eslint-config-un';

export default eslintConfig({
  // This only works with `--config` passed explicitly,
  // otherwise ESLint lints template files with the template's own config
  ignores: ['template/'],
  configs: {
    fileProgress: true,
    markdown: {
      configSentencesPerLine: {
        ignores: [
          'CHANGELOG.md',
          // Putting every sentence on its own line causes line wraps in the changelog
          '.changeset/**/*.md',
        ],
      },
    },
    sonar: true,
    zod: false,
  },
  extraConfigs: [
    {
      files: ['CHANGELOG.md'], // Partially auto-generated by Changesets
      rules: {
        'markdown-preferences/prefer-link-reference-definitions': 0,
        'markdown-preferences/padding-line-between-blocks': 0,
      },
    },
  ],
});
